use std::error::Error;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    
    println!("Hello, world!");

    Ok(())
}

